# Generated by Django 3.1 on 2020-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('cod', models.CharField(max_length=3)),
                ('ag', models.CharField(max_length=5)),
                ('cc', models.CharField(max_length=6)),
            ],
        ),
    ]
